---
# tasks file for helm
- name: Installing git
  yum:
    name: git
    state: latest

- name: Check if Helm is already installed.
  ansible.builtin.stat:
    path: "{{ helm_path }}"
  register: helm_installed

- name: Get the Helm version.
  ansible.builtin.command: "{{ helm_path }} version"
  failed_when: false
  changed_when: false
  register: helm_current_version

- name: Download and expand Helm tarball.
  ansible.builtin.unarchive:
    src: "{{ helm_url }}/helm-{{ helm_version }}-{{ helm_platform }}-{{ helm_arch }}.tar.gz"
    dest: /tmp
    remote_src: true
    mode: 0755
  register: helm_download
  when: >
    not helm_installed.stat.exists
    or helm_version not in helm_current_version.stdout

- name: Copy helm binary to {{ helm_path }}
  ansible.builtin.copy:
    src: "/tmp/{{ helm_platform }}-{{ helm_arch }}/helm"
    dest: "{{ helm_path }}"
    mode: 0755
    remote_src: true
  become: true
  when: helm_download is changed
